### ISSUE TITLE
'printf' "is not recognized as an internal or external command...

### ISSUE THREAD

**Issue by GarkGarcia** [daltonmenezes/hyper-init#1]
I'm on Windows and I get the following message every time I start a _hyper_ window (if I have _hyper-init_ enabled):
`'printf' "is not recognized as an internal or external command, operable program or batch file.`

**Comment by daltonmenezes** [comment]
Hi @GarkGarcia , hyper-init clears the terminal buffer using printf "\\033[H" by default, but you can set it manually adding the `clearCommand: ''` property within the config object. [See it here](https://github.com/daltonmenezes/hyper-init#clearcommand)

In your case you can just do this: `clearCommand: 'cls'`

But your issue was important because I discovered Windows doesn't concatenate commands using &&. Instead of, windows uses "&" and it needs to be fixed on hyper-init. I'll work on it and also I'll make hyper-init recognize Windows and change the clear command to cls automatically. When I have done this patch, I'll close this issue. Thanks.

**Comment by runew0lf** [comment]
any update on this?

**Comment by daltonmenezes** [comment]
Guys, I can't work on this right now. Any pull request is very welcome.

**Comment by daltonmenezes** [comment]
One of the reasons I can't work on it right now: https://www.patreon.com/daltonmenezes

I have to work on other things to feed. Without any support, PR, Patreon or Padrim, I can't devote myself to all my projects.

**Comment by nightmarlin** [comment]
Windows CMD uses `&` but allows for `&&`, PowerShell uses `;` to chain commands. A quick fix is to make a local copy of this plugin in `.hyper_plugins/local`, change the `" && "` (in [/src/join-commands.js](https://github.com/daltonmenezes/hyper-init/tree/master/src)) to the correct concatenator for your normal terminal and use your local plugin by moving hyper-init to `localPlugins`.
I'll see what I can do about changing it to be correct for each terminal type, but no promises

![image](https://user-images.githubusercontent.com/29228454/57465469-956a7480-7276-11e9-9962-818e8c6333a0.png)
